version: '3.3'

services:
  untrunc:
    build: ./backend/untrunc
    container_name: untrunc
    command: python3 app.py
    volumes:
      - ./backend/untrunc/app.py:/app.py
      - VOICE_PASSING:/data
    networks:
      - ssafy-net
    environment:
      - FLASK_DATA_PATH=/data/WebSocket
      - FLASK_FILE_PERIOD=15000
      - FLASK_FILE_DUPLICATE=0
    ports:
      - 8300:8000
volumes:
  VOICE_PASSING:
    external: true

networks:
  ssafy-net:
    external: true